module.exports = {
        LOGIN: 'login',
        LOGGED_IN: 'loggedIn',
        PLAYER_SELECT: 'playerSelect',
        CONFIRM_SELECTED_PLAYERS: 'confirmSelectedPlayers',
        SHOW_VOTE_PHASE: 'showVotePhase',
        VOTE_CONFIRMATION: 'voteConfirmation',
        FAILED_TEAM_VOTE: 'failedTeamVote',
        SUCCESS_FAIL_CONFIRMED: 'successFailConfirmed',
        QUEST_RESULT: 'questResult',
        SHOW_QUEST_PHASE: 'showQuestPhase',
        GAME_STARTED: 'gameStarted',
        NUM_QUEST_PARTICIPANTS: 'numQuestParticipants',
        GAME_PLAYERS: 'gamePlayers',
}